version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  mongodb: # name of the third service
    image: mongo # specify image to build container from
    ports:
      - "27017:27017" # specify port forewarding

  express: #name of the second service
    build: simpleExpress # specify the directory of the Dockerfile
    ports:
      - "8080:8080" #specify ports forewarding
    links:
      - mongodb # link this service to the database service
    depends_on:
      - mongodb
